### ISSUE TITLE
About Waymo experiment

### ISSUE THREAD

**Issue by jiangxb98** [Serenos/LWSIS#3]
How do you handle waymo instance annotations? I use waymo dataset to train the condinst and boxinst on mmdet2.x. But boxinst's mAP is higher then condisnt mAP.I suspect I mishandled the instance annotations.

**Comment by Serenos** [comment]
As a fully supervised segmetation network, CondInst is theoretically superior to BoxInst (weakly supervised), and this point has been proved in the paper. I trained with the official BoxInst repository, which also provides an implementation of CondInst. 
 
For the processing of Waymo instance segmentation data, we also first converted it into COCO format, and then conducted training and evaluation. I have attached the conversion script in the email, which can be run by main.py. So hopefully that answers your questions.

**Comment by jiangxb98** [comment]
收到
